services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - ./user-service:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=user_service_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - pet-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    volumes:
      - ./order-service:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=order_service_db
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - pet-network

  api-gateway:
    image: nginx:latest
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api-gateway/html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - order-service
    networks:
      - pet-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: user_service_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pet-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - pet-network

networks:
  pet-network:
    driver: bridge

volumes:
  db_data:
